dist: trusty
language: rust
cache: cargo
rust:
  - nightly-2018-11-23
env:
  - SETTLE_TIME=2000
script:
  - cargo check --all --all-targets
  - cargo test --all -- --test-threads=1
addons:
  apt:
    packages:
    - liblz4-dev
before_cache:
  - rm -rf /home/travis/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target/incremental

#release

stages:
  if: branch = build_docker_image
  name: release
  services:
    - docker
  script:
    - cargo check --all --all-targets
    - cargo test --all -- --test-threads=1
#  TRAVIS_TAG
  before_install:
    - docker build -t harksin/noria:$TRAVIS_BRANCH .
#master
  deploy:
    provider: script
    script: bash docker_push
    on:
      branch: master