dist: trusty
language: rust
cache: cargo
rust:
  - nightly-2018-11-23
env:
  - SETTLE_TIME=2000
#script:
#  - cargo check --all --all-targets
#  - cargo test --all -- --test-threads=1
#addons:
#  apt:
#    packages:
#      - liblz4-dev
#before_cache:
#  - rm -rf /home/travis/.cargo/registry
#  - rm -rf $TRAVIS_BUILD_DIR/target/incremental



#master
deploy:
  provider: script
  addons:
    apt:
      packages:
        - liblz4-dev
  script:
    - cargo build --release --bin noria-server
    - docker build -t harksin/noria:latest .
    - bash docker_push.sh
  on:
    #master
    branch: build_docker_image